name: coda_wallet
description: Coda wallet for both android and ios, developed by flutter

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  graphql: ^4.0.0-beta.1
  bloc: ^6.0.0
  flutter_bloc: ^6.0.5
  equatable: ^1.1.1
  qr_flutter: ^3.2.0
  qr_code_scanner: ^0.0.13
  flutter_speed_dial: ^1.2.5
  flutter_screenutil: ^3.1.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.12+2
  keyboard_actions: "^3.3.1+1"
  f_logs: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  gql_code_gen: ^0.1.5
  mockito: ^4.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - images/coda_logo.png
    - images/lock-normal.png
    - images/unlock-normal.png
    - images/appbar_back.png
    - images/txsend.png
    - images/txreceive.png
    - images/locked.png
    - images/unlocked.png
    - images/qr_scan.png
    - images/qr_scan1.png
    - images/qr_scan2.png
    - images/contact_address.png
    - images/locked_black.png
    - images/unlocked_green.png
    - images/setting.png
    - images/delete.png
    - images/edit_name.png
    - images/tx_failed.png
    - images/tx_pending.png
    - images/tx_success.png
    - images/tx_timeout.png
    - images/tx_unsubmit.png
    - images/navigate_next.png
    - images/staking.png

  fonts:
   - family: Entypo
     fonts:
       - asset: fonts/Entypo.ttf
         weight: 700
   - family: EvilIcons
     fonts:
       - asset: fonts/EvilIcons.ttf
         weight: 700
   - family: Feather
     fonts:
       - asset: fonts/Feather.ttf
         weight: 700
   - family: FontAwesome
     fonts:
       - asset: fonts/FontAwesome.ttf
         weight: 700
   - family: Foundation
     fonts:
       - asset: fonts/Foundation.ttf
         weight: 700
   - family: Roboto-Regular
     fonts:
       - asset: fonts/Roboto-Regular.ttf
         weight: 400
   - family: NotoSans-Regular
     fonts:
       - asset: fonts/NotoSans-Regular.ttf
         weight: 700
   - family: Lato-Light
     fonts:
       - asset: fonts/Lato-Light.ttf
         weight: 300
